### PR TITLE
Full deployment script

### PR DESCRIPTION
**Pull request by carterm**
Update to deployment

Sample run here...
https://github.com/cagov/covid-static-data/runs/3737472862?check_suite_focus=true

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
Great simplification of yml!

The sample run is really helpful for review, thanks

Nice commit history

**Comment by carterm** [comment]
> Great simplification of yml!
> 
> The sample run is really helpful for review, thanks
> 
> Nice commit history

Had to do some learning.  Should be good from now on.

**Comment by aaronhans** [comment]
Want to double check this is not doing any deletion when it uploads because covid-static is putting all the pdfs in the same azure blob storage

**Comment by aaronhans** [comment]
These settings on the upload github action should cover not deleting stuff:

          path: path/to/artifact
          cleanup: false
          sync: false

**Pull request merged**
